config/routes.rb
WealthOZ201::Application.routes.draw do

  resources :budgets

  resources :ledgers do
    collection do
      get :report_balance
      get :report_plm
      get :report_plwu
      get :report_kpi

    end
  end

  resources :cut_off_wealths

  resources :future_reports, only: [:index] do
    collection do
      get :future_balance
      get :actual_budget
    end
  end

  resources :transparents, only: []  do
  collection do
      get :report_balance
      get :report_plm
      get :report_plwu
      get :report_kpi
      get :report_story
    end
  end
  match '/transparent',   to: 'transparents#report',   via: 'get'

  match '/report',   to: 'ledgers#report',   via: 'get'
  match '/wealthoz',   to: 'ledgers#wealthoz',   via: 'get'
  match '/wealth_index',   to: 'ledgers#wealth_index',   via: 'get'
  resources :fxes
  resource :group do
    resources :group_users, controller: 'groups/group_users', only: [:index] do
      member do
        get :approved
      end
    end
  end

  resources :users do
    member do
      get :following, :followers
    end

  end
  resource :group_user

  resources :relationships, only: [:create, :destroy]

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :projects
  resources :accounts do
    collection do
      get :check
    end
  end

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/why',    to: 'static_pages#why',    via: 'get'
  match '/how',   to: 'static_pages#how',   via: 'get'
  match '/manage_groups',   to: 'static_pages#manage_groups',   via: 'get'

  match '/donate',   to: 'static_pages#donate',   via: 'get'

  match '/book',   to: 'static_pages#book',   via: 'get'
  match '/a2',   to: 'static_pages#a2',   via: 'get'
  match '/a3',   to: 'static_pages#a3',   via: 'get'

  match '/b1',   to: 'static_pages#b1',   via: 'get'
  match '/d1',   to: 'static_pages#d1',   via: 'get'
  match '/d2',   to: 'static_pages#d2',   via: 'get'

  match '/d4',   to: 'static_pages#d4',   via: 'get'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if signed_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def why
  end


  def how
      data_table = GoogleVisualr::DataTable.new
      data_table.new_column('string'  , 'Label')
      data_table.new_column('number'  , 'Value')
      data_table.add_rows(3)
      data_table.set_cell(0, 0, 'Leverage' )
      data_table.set_cell(0, 1, 80)
      data_table.set_cell(1, 0, 'ROI')
      data_table.set_cell(1, 1, 55)
      data_table.set_cell(2, 0, 'Savings')
      data_table.set_cell(2, 1, 68)

      opts   = { :width => 800, :height => 240, :redFrom => 80, :redTo => 100, :yellowFrom => 50, :yellowTo => 80, :minorTicks => 5 }
      @chart = GoogleVisualr::Interactive::Gauge.new(data_table, opts)


  end

  def manage_groups

  end

  def donate

  end

  def demo2
  end

  def demo3

  end

  def demo4

  end

  def demo5

  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/a2.html.erb
<div class="jumbotron">
  <%= link_to "Table of Content",    book_path %>
  <hr>

<h1 class="western" lang="en-US">Having contradictory ideas in your head</h1>
<br>
  <div style="text-align: center;">
    <img src="http://i.imgur.com/XLDYNbr.gif" width="50%" height="50%" align="middle" title="contradictory ideas" />
  </div>
<p class="western" lang="en-US">
  Having contradictory ideas is really hard for us humans. It is confusing, depressing and makes us feel very uncomfortable.
  We all hear that we have to challenge our self’s and our ideas and that all the great innovations and discoveries are been
   made by challenging the status quo (the current situation and the current believes). But how hard is that?
</p>

<p class="western" lang="en-US">
  Challenging the status quo means that you have contradictory ideas in your head. It means that you are a little bit
   uncertain about the knowledge and you want to test this knowledge.
</p>

<p class="western" lang="en-US">
  I would like to stress on the following: having two contradictory ideas in your head is not like believing that
  both of them are true. It simply means that you do not know which one is true.
</p>

<p class="western" lang="en-US">
  Believing simultaneously in two controversial ideas leads to psychological problem called Cognitive dissonance which is
  utilized by political propaganda and extreme religious believes (yes, a brain washing technique like get them confused and
  uncertain and then give them “your cure”).
</p>

<p class="western" lang="en-US">
  The thing is that we all have to balance between believes and uncertainty. Over-believing (if such word exists) may
  leads to absence of progress and extreme religions. Too much uncertainty leads to all sorts of phobias, fears and lack
  of initiative. Good luck in balancing that :) and cheer up.
</p>

<p class="western" lang="en-US"><i>
  I don’t believe that that I have all the answers but I would like to help you in asking the right questions by
   broadening your views. And yes I am going to write about contradictory ideas as ideas have to be challenged.
</i></p>

<p class="western" lang="en-US">
  <u>  Some Questions for you</u>:
   How often you challenge your believes? How certain and confident you are in your actions?
</p>



<hr>
<%= link_to "Table of Content",    book_path %>
</div>

app/views/static_pages/a3.html.erb
<div class="jumbotron">
  <%= link_to "Table of Content",    book_path %>
  <hr>

<h1 class="western" lang="en-US">The right order</h1>
<br>
  <div style="text-align: center;">
    <img src="http://i.imgur.com/67nOBeu.gif" width="50%" height="50%" title="the right order" />
  </div>
  <p class="western" lang="en-US">
    We all know that the order matters. Take for example a cocking recipe you’ve got the list of all the
    ingredients but what will happen if you start the manipulations in the wrong order like first you roast
    the meat then you boil it and then you cut it to pieces. At the end you will probably end up with something
    uneatable or at least a new kind of dish. So as in most of the processes the order is as much important as the
    individual ingredients. Learning makes no difference.
  </p>

  <p class="western" lang="en-US">
    <i>I recommend you to read my articles in proper order so that you can have maximal benefits of them. In other words,
      just follow the process of wealth generation (understand, measure, manage and explore).
    </i>
  </p>
  <p class="western" lang="en-US">
    Sorting and arranging things on the other hand is hard, sometimes impossible or even unnecessary thing to do if the
    common properties of the categories are uncertain, vague or unimportant (scientist are still having debate over
    categorizing some spices as plants or animals) .
  </p>

  <p class="western" lang="en-US">
    <u>Some Questions for you</u>: Is your home library ordered? Is your hard disk space ordered? Have you seen the movie “Memento”?
  </p>


<hr>
<%= link_to "Table of Content",    book_path %>
</div>

app/views/static_pages/b1.html.erb
<div class="jumbotron">
  <%= link_to "Table of Content",    book_path %>
  <hr>

<h1 class="western" lang="en-US">Point Zero</h1>

<br>
<div style="text-align: center;">
  <img src="http://i.imgur.com/no84Sw2.gif" title="0"  width="50%" height="50%" />
</div>

<h2 class="western"></h2>
<p>
  In the MEASURE section of this site I shall write all about the practical, technical and boring stuff about measuring
  our WEALTH. I do not plan for any stories or even jokes.
</p>

<p>Most of the drawings shall be tables, charts and numbers together with the entire Greek alphabet. BEWARE.</p>

<p>
  While trying to be funny and interesting I really strive for excellence.
</p>

<p>
  The intimate idea behind all this is to construct a model (a model behind WealthOZ) for wealth measuring. I consider
  measuring an important milestone on our road to WEALTH as one can only manage things that he/she measures.
</p>

<p>
  As a beginning I plan to start with the material part of it -  in other words accounting and budgeting. Maybe a
   boring words to some of you but they really matter. I consider Financial discipline as equal important as money
   making because a wealthy person is not a person that has what she wants but rather a person that do not wants what
   she do not have(a little bit philosophical here).
</p>

<p>
  I have a lot of ideas but lets take it a step of a time. Lets walk the whole road (whatever the road is) and of
  course your constructive feedback is crucial success factor.</p>

<p>
  How to write me? : <%= link_to "Register", signup_path %> (<strong>totally free!</strong> ) and write a public post disusing  your ideas and feedback in short.
</p>

<p>Thank you all in advance!</p>


<hr>
<%= link_to "Table of Content",    book_path %>
</div>

app/views/static_pages/d1.html.erb
<div class="jumbotron">
  <%= link_to "Table of Content",    book_path %>
  <hr>

  <h1 class="western" lang="en-US">Short Kibitzer Theory</h1>
  <br>
  <div style="text-align: center;">
    <img src="http://i.imgur.com/oRciNcC.jpg" width="50%" height="50%" align="middle" title="contradictory ideas" />
  </div>


  <p>It was a sunny day so </span><span lang="en-US"><u>Tomas</u></span><span lang="en-US"> decided to go for a walk in the park.
     After short break on a bench he felt refresh and a need for new mind challenge emerge. He went to the open chess tables.
      The chess players in the park were usually people not doing well in life. You can call them losers but they have devoted
      their lives to the game of chess which they claimed is the game of all games and that it has real life applications like
       politics, war and business. It was strange that no professional chess play was ever good in something else
       except other games.</p>

  <p>Tomas find a free semi-professional chess opponent and they started to play. At the begging Tomas was doing
    pretty well but then kibitzers gathered around the table. These kibitzers were discussing the game on a loud
    voice and they were giving their unwanted advices which were varying from good to terrible. Tomas got annoyed
     and he lost the game.</p>

  <p>Dam you fucking kibitzers”: Thomas thought to himself “I should stick to the online chess”</p>

  <p>He stood up a saw another chess table full of kibitzers. But these kibitzers were different –
    they were quite. Tomas go close and saw that the chess players on that table were playing
    for money. Thomas went home and that evening only kibitzer’s thoughts were in his head .
     And he started to make parallels between chess, politics and modernity problems:</p>

  <ol>
    <li><p><b>Politics modernity problems</b></p></li>
  </ol>
  <p>What is the one thing that I really hate about our modern times –
    it is called politics. But why I hate politics so much:</p>
  <ul>
    <li><p>Because there are bunch of people that are “no good for anything” making
      large scale decisions affecting all of us</p></li>

    <li><p>The politics claim that they are elected in a democratic process and that
      they will represent the voters believes, needs and ideas by applying inline actions called politics.</p></li>

    <li><p>So once in a while there are these elections where you can choose from one to another politician with
      different types of ideas and programs that they claim they will execute. Shortly after a politician is elected
      they all start doing common things like: lobbing for corporate interests, taking bribes and even doing opposite t
      hings they have promised initially.</p></li>

    <li><p>But maybe the worst thing of all is that after they do all that (doing unethical things
      and not keeping to a promise) they start showing everywhere <b>disturbing your life</b>
       while explaining that the decisions they make are the right ones even the
        only right choice. Come on you are full of shit and you know it.
        This mass propaganda is been deployed with the help of other group of people called journalists.</p></li>
  </ul>
  <p>So the system is broken and it is not that some countries are doing it wrong.
    <b>It is all over the world</b></p>

  <p>You are given the right to choose from the same kind of dirty and mean people.
    There may be exceptions but eventually the system kicks them out or assimilates them.
    Eventually you do not chose ideas or politics you chose only dirty people to govern you.</p>

  <p><b>Why we are here?</b></p>

  <p>Let’s revise how it was:</p>

  <p>Democracy was born in ancient Greece. There in relatively small
     and independent city-states the decisions were made via voting from all those who have
      rights. The voting process was simple and personal and it was conducted at a public place
      were all the voters were gathered and everyone was able to see everyone while voting.</p>

  <p>As the counties become bigger and bigger we had to invent t institutions like Parliament, Senate,
    Chamber, and Party and eventually the current voting process.</p>

  <p>But why is the modern democracy so different from back then? I’ve got three things for you:</p>
  <ol start="1" type="A">
    <li><p>The big is different from the small</p></li>
  </ol>
  <p>This may sound obvious but is it very deep problem that needs a whole new article.</p>
  <ol start="2" type="A">
    <li><p>Top-down vs. Bottom-up </p></li>
  </ol>
  <p>It is the way how important decisions are been made. Another huge topic.</p>
  <ol start="3" type="A">
    <li><p>The Kibitzer effect. </p></li>
  </ol>
  <p>Finally we got to the kibitzers. You know <b>kibitzes: anonymous people that are giving unwanted
    advices without betting anything</b>. It looks like we are surrounded by them – politicians,
    business consultants, journalists, non-government organizations and so on. But let’s stick to the political domain. </p>

  <p>Modern politics is the opposite of money-chess-game in the park. Here the kibitzers are making all the
     decisions and they are betting your tax money. Other kibitzers called journalist are discussing
     and communicating the decisions made by the first group of kibitzers. The biggest problem is that
     we are all becoming kibitzers but only for very short period of time – when talking about politics in
     the pub and when voting on elections (remember: <b>anonymous people that are giving unwanted advices without
       betting anything</b>.</p>

  <p>So we are kibitzers for 5 min. while others are kibitzers for life while taking millions of dollars of our money. Lovely</p>

  <p>People in the park have inner understanding that kibitzers should never been given the right to speak.
    Now try to silence a politician or a journalist and the whole world will understand how nondemocratic you are. </p>

  <p><b>It is just that “Representatives become Kibitzers”.</b></p>

  <p>So the problems that are mentioned are defined way better and broadly by <u>N.N.Taleb</u>. All I did was
    to put them in the context and hopefully to get your attention on them.</p>

  <p>Defining the problem and asking the right questions is far more important than giving
    solutions and answers coz good answers and solutions may change over time but important questions never change.</p>

  <ol start="2">
    <li><p><b>The Solution</b></p></li>
  </ol>

  <p>Let’s see how Mother Nature solves complicated problems compared to modernity:</p>
  <table width="691" cellspacing="0" cellpadding="8"><colgroup><col width="328" /> <col width="329" /> </colgroup>
    <tbody>
      <tr valign="top">
        <td width="328"><p><b>NATURE</b></p></td>
        <td width="329"><p><b>MAN-MADE</b></p></td>
      </tr>
      <tr valign="top">
        <td width="328"><p>High complexity but no kibitzers</p></td>
        <td width="329"><p>High complexity and prosperity of the kibitzers</p></td>
      </tr>
      <tr valign="top">
        <td width="328"><p>Keep problems local</s></td>
        <td width="329"><p>Globalization leads to global problems</p></td>
      </tr>
      <tr valign="top">
        <td width="328"><p>Makes systems that adjust to errors</p></td>
        <td width="329"><p>Try to make robust systems</p></td>
      </tr>
      <tr valign="top">
        <td width="328"><p>Decisions are bottom-up (evolution)</p></td>
        <td width="329"><p>Decisions are top-down</p></td>
      </tr>
    </tbody>
  </table>
  <p>

  </p>
  <p>We are in the information era and with the help of the Internet we can communicate instantly.</p>

  <p><b>IDEA: “Crowd-source politics”</b></p>

  <p>Why not create a political Party where its politician will have only one job…. to ask proper
    questions. And that is a very hard job. On the other side all party members will vote personally meaning
    that everyone can review what others have voted. Than the politicians will just vote what their party members
     have voted in the Parliament/Senate. Let focus on battles of ideas within a Party and not on battles between
     individuals between Parties.</p>

  <p>Anonymity leads to reckless decisions. If you really believe in something you should stand up with your name at least. </p>

  <p>In this complicated world “not knowing” is not a sin so quorums should be really low or should be removed.
     Vote only if you know it is right or you deeply believe in it and you are willing to put your name on it. </p>

  <p>The quality of the decisions made by the voters should be reviewed and appraised by the very same voters.
    People making constantly bad decisions should be penalized (like ban them from the voting process for a period of time).</p>

  <p><b>In this kind of decision-making-voting process I would like to participate –
    personal, transparent and with no kibitzers. </b></p>

  <p>Executing this idea in an online platform should be a hard task. A lot of details have to be taken
    under consideration and the idea has to be polished. One thing is certain:</p>

  <p><b>If someone creates such a system I shall definitely use it.</b></p>

<hr>
<%= link_to "Table of Content",    book_path %>
</div>

app/views/static_pages/d2.html.erb
<div class ="row">
  <div class="col-md-6">
  <%= link_to "Table of Content",    book_path %>
  <hr>

  <h1 class="western" lang="en-US">Invisibility vs. Transparency</h1>
  <br>
  <div style="text-align: center;">
    <img src="http://i.imgur.com/kF009JH.jpg"  width="50%" height="50%" align="middle" title="transsparent"/>

  </div>

  <p>You know invisibility. You’ve seen it in movies where the good or the bad guy has this supernatural ability.
  Everyone had wished to become invisible for a moment (so he can sneak in the girls changing-room for example).</p>

  <p>So you have invisibility if you can see them and they can’t. This gives you huge advantages which you can exploit if you wish.</p>

    <p>Transparent on the other hand is an object through who you can see (like glass or water). It is there and you know it but it
   has no color of its own and you can see what is behind it. Transparent objects are not of a big interest to your eyes.</p>

   <p>Transferring these two terms into social life is not a big mind challenge. Social and business invisibility will give you
  huge advantage over your competitors and all the people you are interacting with. You will know things they hide. But if
  everyone is invisible: all the social interactions would be impossible due to obvious reasons (no one can see anyone).</p>

  <p>Transparent on the other hand is a very buzz word. In the social aspect this basically means that you are showing everything
   you’ve got (not hiding anything). This automatically makes you vulnerable. In a long run transparent agents can have mutual
   beneficial interactions only with other transparent agents (take for example nudist).</p>

   <p>In our modern times where we have instant communication and access to information, invisibility is becoming really hard thing
   to do. That is why more and more people have information about what we want to show plus a lot of stuff we do not want to show.</p>

   <p>Transparency inevitably leads to inequality. If everyone knows were the best prices are, everyone will shop there which leads
  to the “winner-takes –it-all” effect.</p>

  <p>Transparency is not full you know. That is why the modern-business-trade-off is to be very transparent about your customers’
   relationships and hide deeply how you actually make profit. How Google, Facebook, Nestle, all the TV channels, banks and etc.
    are making profit? They give you constant info: how low their prices are or what kind of green initiatives they have but you
    have no idea how they use you data, what kind of ingredients they use or how much interest you actually have to pay. Just do
     not be fooled by this semi-transparency.</p>

  <p>For almost a year I am building a personal financial application (WealthOZ). For a non-programmer like me it is a
  complicated and lonely job but I am determined to do it. The thing is that I want to embed most of the things I write about.</p>

  <p>I want people to write their financial transactions in the system then help them manage their money and eventually
  increasing their wealth. It is obvious that we have a transparency issue here. I want people to be financially transparent
   to WealthOZ so WealthOZ has to be financially transparent to them.  Following the principle of mutual-transparency:
   I have to provide <%= link_to "my aggregated financial information",    transparent_path %> to all WealthOZ users.</p>

   <p>We cannot increase our common wealth if we do not cooperate. We cannot cooperate if we do not trust each other. Sustainable
  trust is built on mutual transparency.</p>


<hr>
<%= link_to "Table of Content",    book_path %>
</div>
</div>

app/views/static_pages/d4.html.erb
How to lose

Thomas: Today I would like to educate you on special topic on which I consider myself as specialist.
    And that is <b>losing</b>.

Garret:  Honestly you look like a pro.  :)


Thomas: As 99% of all creative thing fail so is with 98% of all new business.
To succeed in such a “game” you’d better be prepared for a lot of
<b>trails and errors.Trial and error is freedom my friend. </b>
The more trial and errors you have the biggerthe possibility to succeed in something The world
is changing. We are not farmers or workers on the production line any more (at least most of us).
If you look at most of the successful people in the world you would find that they have a lot of failures
and eventually they succeed. So the failures are all around us and recovering from them is vital
for our survival it may be a good idea to learn how to fail. Here are 5 killer steps in mastering losing:

<ol>
  <li>Define big goals.</li>
  <li>Break down you big goals into smaller assumptions or actions.</li>
  <li>Limit your losses</li>
  <li>Evaluate your loss and refocus. See what you have gained while losing</li>
  <li>Go out and fail gain.</li>
</ol>
&nbsp;

Being prepared for allot of trails and errors means that you
have to mitigate the problems of losing mentally and financially. Losing mentally is really hard.
Every loss damages our ego plus nobody likes the losers. Our brains are wired evolutionary to avoid
losing and promote wining. That is why most of our decisions are targeting emotional balance between
losses and wins rather than best outcome.

Sarah: Is it possible to have more wins than losses and have a negative
total outcome? Yes <b>if the stakes are different</b>.  Avoiding negative emotional misbalance
leads to planning for small but relatively constant and easy wins. That is why people prefer to
work for salary than being entrepreneurs. Studies have found that one loss is equal approximately
2.5 wins on our emotional scale. This explains why gambles who also are looking for emotional balance
rather than financial outcome eventually lose their money. When you detach your emotional fear of losing
(which actually can be only limited as we are only humans) losing financially is far more easy. It is all
about numbers and the only question that you have to answer is how much money I can afford losing

  Thinking in could help)? Applying a financial strategy where you make a lot of small losses
   with little harm may be a smart thing to do.

   Sri Humana: What about apply a <b>life </b>strategy where you make a lot of small mistakes with
   little harm?

   <span style="text-decoration: underline;">Some Question for you</span>: Which is the best way of learning though
   success stories or through stories of failure?  Do you know people that feel comfortable losing?

app/views/static_pages/demo2.html.erb
<section>
<ul class="nav nav-tabs" style="margin-bottom: 15px;">
  <li class="active"><a href="#home" data-toggle="tab">Future Balance WU</a></li>
  <li><a href="#profile" data-toggle="tab">Future P&L</a></li>
  <li><a href="#profile" data-toggle="tab">Actual vs. Budgeted</a></li>
  <li><a href="#profile" data-toggle="tab">Future CAPEX</a></li>
  <li><a href="#profile" data-toggle="tab">Trial Balance</a></li>
</ul>
</section>
<div id="myTabContent" class="tab-content">
  <div class="tab-pane fade active in" id="home">
    <p>Raw denim you probably haven't heard of them jean shorts Austin. 
    	Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, 
    	williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. 
    	Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. 
    	Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.</p>
  </div>
  <div class="tab-pane fade" id="profile">
    <p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. 
    	Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four 
    	loko farm-to-table craft beer twee. Qui photo booth letterpress, commodo enim craft beer mlkshk aliquip 
    	jean shorts ullamco ad vinyl cillum PBR. Homo nostrud organic, assumenda labore aesthetic magna 
    	delectus mollit.</p>
  </div>

</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<% if signed_in? %>
  <div class="row">
    <aside class="col-xs-3">
      <section>
        <%= render 'shared/user_info' %>
      </section>
       <section>
        <%= render 'shared/stats' %>
      </section>

      <section>
        <%= render 'shared/micropost_form' %>
      </section>
      <section>

      </section>
    </aside>
    <div class="col-xs-5">
      <h4>FuturePosts Feed</h4>
      <%= render 'shared/feed' %>
    </div>


  </div>
<% else %>

<div class="center jumbotron">

	<%= render 'shared/video_youtube' %>

	<h3>"Wealth OZ" a financial app that solves the two most
		difficult and important financial problems out there."
	</h3>
	<%= link_to "Sign up it's free!", signup_path , class: "btn btn-success btn-lg" %>
	<h3>The Wealth Problem</h3>
	<p class="text-warning">People do not know their WEALTH !!!</p>

	<h3>The Consolidation Problem</h3>
	<p class="text-warning">People can't summarize their GROUP WEALTH !!!</p>


  <div class="row">
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <h1><span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span></h1>
        <div class="caption">
          <h3>Wealth-Driven</h3>
          <p>...</p>

        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <h1><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span></h1>
        <div class="caption">
          <h3>Collaborative</h3>
          <p>...</p>

        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <h1><span class="glyphicon glyphicon-gift" aria-hidden="true"></span></h1>
        <div class="caption">
          <h3>Free</h3>
          <p>...</p>

        </div>
      </div>
    </div>
  </div>

</div>
<% end %>

app/views/static_pages/manage_groups.html.erb
<% provide(:title, 'Group Settings') %>

<h3>Manage Your Group Settings</h3>


  <div class="btn-group-vertical">
    <aside class="span8">
    <section>
        <%= render 'shared/user_info' %>
    </section>
    <section>
    	<%= link_to "Create New Wealth Group", new_group_path , class: "btn btn-success" %>
    	<br>
    	<br>
    	<%= link_to "Link to an existing Wealth Group",edit_user_path(current_user) , class: "btn btn-success" %>
    	<br>
    	<br>	
    	<%= link_to "Manage Projects",new_project_path(current_user) , class: "btn btn-success" %>
    	<br>
    	<br>	
		<%= link_to "Manage Accounts",accounts_path , class: "btn btn-success" %>
    </section>

      
    </aside>
  </div>