config/routes.rb
WealthOZ201::Application.routes.draw do

  resources :budgets

  resources :ledgers do
    collection do
      get :report_balance
      get :report_plm
      get :report_plwu
      get :report_kpi

    end
  end

  resources :cut_off_wealths

  resources :future_reports, only: [:index] do
    collection do
      get :future_balance
      get :actual_budget
    end
  end

  resources :transparents, only: []  do
  collection do
      get :report_balance
      get :report_plm
      get :report_plwu
      get :report_kpi
      get :report_story
    end
  end
  match '/transparent',   to: 'transparents#report',   via: 'get'

  match '/report',   to: 'ledgers#report',   via: 'get'
  match '/wealthoz',   to: 'ledgers#wealthoz',   via: 'get'
  match '/wealth_index',   to: 'ledgers#wealth_index',   via: 'get'
  resources :fxes
  resource :group do
    resources :group_users, controller: 'groups/group_users', only: [:index] do
      member do
        get :approved
      end
    end
  end

  resources :users do
    member do
      get :following, :followers
    end

  end
  resource :group_user

  resources :relationships, only: [:create, :destroy]

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :projects
  resources :accounts do
    collection do
      get :check
    end
  end

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/why',    to: 'static_pages#why',    via: 'get'
  match '/how',   to: 'static_pages#how',   via: 'get'
  match '/manage_groups',   to: 'static_pages#manage_groups',   via: 'get'

  match '/donate',   to: 'static_pages#donate',   via: 'get'

  match '/book',   to: 'static_pages#book',   via: 'get'
  match '/a2',   to: 'static_pages#a2',   via: 'get'
  match '/a3',   to: 'static_pages#a3',   via: 'get'

  match '/b1',   to: 'static_pages#b1',   via: 'get'
  match '/d1',   to: 'static_pages#d1',   via: 'get'
  match '/d2',   to: 'static_pages#d2',   via: 'get'

  match '/d4',   to: 'static_pages#d4',   via: 'get'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>

  
  <%= will_paginate @feed_items %>

<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
<% if Time.now > feed_item.post_date %>
	<div id="feed" >
	  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
	  <span class="user">
	    <%= link_to feed_item.user.name, feed_item.user %>
	  </span>
	  <span class="topic">Topic: <%= feed_item.topic %></span>
	  <span class="content" ><%= feed_item.content %></span>
	  <span class="timestamp">
	    Posted <%= time_ago_in_words(feed_item.created_at) %> ago concerning <%= feed_item.post_date %>
	  </span>
	</div>
<% else %>
	<div id="feed" style="background-color: #e8e8e8    ;">
	  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
	  <span class="user">
	    <%= link_to feed_item.user.name, feed_item.user %>
	  </span>

	  <span class="topic">Topic: <%= feed_item.topic %></span>
	  <span class="content">The Content will be available on: <%= feed_item.post_date %></span>
	  <span class="timestamp">
	    Posted <%= time_ago_in_words(feed_item.created_at) %> ago concerning <%= feed_item.post_date %>
	  </span>
	</div>
  <% end %>
</li>

app/views/shared/_group_form.html.erb
<h4>Create New Wealth Group:</h4>


<%= form_for(@group, url: group_path) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :name, placeholder: "Wealth Group Name" %>
<br>

    <%= f.collection_select(:fx_id, Fx.all, :id, :fx ) %>
    <%= f.label :fx_id, "Choose currency" %>
<br>
  </div>
  <%= f.submit "Save", class: "btn btn-sm btn-success" %>
<% end %>

app/views/shared/_help_assets.html.erb
<div class="modal fade bs-example1-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
		<div class="modal-header">
        	<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        	<h4 class="modal-title" id="myModalLabel">Assets</h4>
      	</div>
      	
<a class="btn btn-success assets" href="#" rel="tooltip" data-placement="right"
title="Increase(+) Decrease(-)">Assets</a>
<a class="btn " href="#" rel="tooltip" data-placement="bottom"
title="Increase(-) Decrease(+)">-Debt</a>
<a href="#">=</a>
<a class="btn " href="#" rel="tooltip" data-placement="bottom"
title="Increase(+) Decrease(-)">Income</a>
<a class="btn " href="#" rel="tooltip" data-placement="bottom"
title="Increase(-) Decrease(+)">-Expenses</a>
<a href="#">=</a>
<a class="btn " href="#" rel="tooltip" data-placement="bottom"
title="Increase(+) Decrease(-)"><strong>Wealth</strong></a>



			<p><strong>Things we own</strong> – are generally things that have a monetary value 
			(can be easily measured in money), <underline>they are sellable and/or enables us to generate income</underline>. 
			So all the significant things we own are called <strong>ASSETS</strong>. – Examples: car, house, shares in company, cash…</p>
			<br />
			<p><q>You Increase an Asset with [+] and you decrease it with [-]</q></p>
			<br />
     		<p><strong>Example:</strong> You buy a laptop and you pay in cash 500. So you have [+]500 laptop and [-]500 cash  </p>
     
     		<p><strong>How to distinguish if the money I spend are expenses or assets?</strong></p>
     		<p>It is up to you to decide. First look at the assets definition and if the money spent do not meet 
     		the criterias it is an expense. Here are some questions that can help you differentiate assets from expenses:</p>
			
				<p>Do you expect any income from your asset or is it a tool for income generation?</p>
				<p>Does it have significant material value?</p>
				<p>Do you expect it to have a significant material value after a year?</p>
				<p>Can you sell it after a long period of time (say a year)?</p>
			
			<p>If you have answered with Yes to some or all of the questions above 
			you probably have bought an asset.</p>

     
    </div>
  </div>
</div>

app/views/shared/_help_expenses.html.erb
<div class="modal fade bs-example4-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
		<div class="modal-header">
        	<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        	<h4 class="modal-title" id="myModalLabel">Expenses</h4>
      	</div>

<a class="btn  assets" href="#" rel="tooltip" data-placement="right"
title="Increase(+) Decrease(-)">Assets</a>
<a class="btn " href="#" rel="tooltip" data-placement="bottom"
title="Increase(-) Decrease(+)">-Debt</a>
<a href="#">=</a>
<a class="btn " href="#" rel="tooltip" data-placement="bottom"
title="Increase(+) Decrease(-)">Income</a>
<a class="btn btn-warning" href="#" rel="tooltip" data-placement="bottom"
title="Increase(-) Decrease(+)">-Expenses</a>
<a href="#">=</a>
<a class="btn " href="#" rel="tooltip" data-placement="bottom"
title="Increase(+) Decrease(-)"><strong>Wealth</strong></a>
       	
      	
			<p><strong>EXPENSES </strong>– is money you spend or the cost incurred. 
			So the money you spend are generally called expenses but in some cases you can call them assets.</p>
  				   
     		<p>Examples: all kinds of services, used materials, taxes, financial costs…</p>
			<br />
			<p class="text-warning">You Add Expenses with [-] and you Remove/Reverce them with [+]</p>
			<br />
     		<p><strong>Example:</strong> You pay your rent in cash 800. So you have [-]800 rent and [-]800 cash</p>
     		<p>Ultimatly your Wealth decrease with 800!</p>
     
     
     		<p><strong>How to distinguish if the money I spend are expenses or assets?</strong></p>
     		<p>It is up to you to decide. First look at the assets definition and if the money spent do not meet 
     		the criterias it is an expense. Here are some questions that can help you differentiate assets from expenses:</p>
			
				<p>Do you expect any income from your asset or is it a tool for income generation?</p>
				<p>Does it have significant material value?</p>
				<p>Do you expect it to have a significant material value after a year?</p>
				<p>Can you sell it after a long period of time (say a year)?</p>
			
			<p>If you have answered with Yes to some or all of the questions above 
			you probably have bought an asset.</p>
     
    </div>
  </div>
</div>

app/views/shared/_help_income.html.erb
<div class="modal fade bs-example3-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
		<div class="modal-header">
        	<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        	<h4 class="modal-title" id="myModalLabel">Income</h4>
      	</div>
<a class="btn " href="#" rel="tooltip" data-placement="right"
title="Increase(+) Decrease(-)">Assets</a>
<a class="btn " href="#" rel="tooltip" data-placement="bottom"
title="Increase(-) Decrease(+)">-Debt</a>
<a href="#">=</a>
<a class="btn btn-success assets" href="#" rel="tooltip" data-placement="bottom"
title="Increase(+) Decrease(-)">Income</a>
<a class="btn " href="#" rel="tooltip" data-placement="bottom"
title="Increase(-) Decrease(+)">-Expenses</a>
<a href="#">=</a>
<a class="btn " href="#" rel="tooltip" data-placement="bottom"
title="Increase(+) Decrease(-)"><strong>Wealth</strong></a>

<br />
<p><strong>INCOME</strong> – generally said the net economic benefits that you have received. 
Income usually relates to cash inflows but not all your cash inflows are income. 
When you go to the store and you buy a candy that costs 1$ with 5$ bill the 4$ you received back 
is not an income. The loans and borrowing you receive are not income also (Remember that). 
So income relates to the benefits.</p>
 <br />
 <p><strong>You Increase your Income with [+] and you decrease it with [-]</strong></p>
 <br />
<p><strong>Examples of income:</strong> salary, interest received, dividends received, rent received and etc.
			You receive your wage of $2000 in your bank account. This means cash [+]2000, income from wages [+]2000 
			and ultimatly you Wealth increases [+]2000</p>
     
    </div>
  </div>
</div>

app/views/shared/_help_wunits.html.erb
<a data-toggle="modal" data-target=".bs-example124-modal-lg">*Wealth Units</a>

<div class="modal fade bs-example124-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
		<div class="modal-header">
        	<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        	<h4 class="modal-title" id="myModalLabel">Wealth Units</h4>
      	</div>
      	
<p>Wealth Units are all the People, Projects and Entetis who measure their Group Wealth. 
They are all in one Wealth Group and percieve thier transactions as mutual transactions.</p>
<br />
<p>If we want to measure the Wealth of a group of individuals and entities all the members of the group 
have to perceive the total Wealth of the group as <b>mutual Wealth</b>. It means that the relationships 
within the group are very very strong and all the members are willing to measure their Wealth as a group. 
These relationships can be something like family relationships, entity and owners relationships or  
all other relationships where the members of the group perceive their total Wealth as <b>mutual Wealth.</b></p>
<br />
<p>But how to be sure that our inner transactions can be accounted as group transactions?</p>
<br />
<p>Just answer this question: Do I perceive these inner transactions as income/expense or 
just a money transfer (from one of my pockets to the other)? Do I perceive the money I pay to my 
children as expense or just a money transfer?  Do I perceive the money I receive from my father as 
income and etc? The thing is that all group members have to have the will to measure their mutual wealth 
(one can do the work but all the others must provide him with information).</p>
     
    </div>
  </div>
</div>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  
  <div class="field">  
    <%= f.text_field :topic, placeholder: "A Future Topic..."%>
   </div>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose something about the Future... Try to predict something or surprize someone!" %>
  </div>
     
	<div class="field" >
	    <%= f.text_field :post_date, 'data-behaviour' => 'datepicker', placeholder: "Future Post Date"%>
	</div>
	
	<script type="text/javascript">
	  $('[data-behaviour~=datepicker]').datepicker({
	  	 	weekStart: 1,
			autoclose: true,
			format:'yyyy-mm-dd' ,
			todayHighlight: true   
	  });
	</script>
  
  <%= f.submit "Post", class: "btn btn-large btn-success" %>
<% end %>

app/views/shared/_projects_form.html.erb
<% provide(:title, 'Create New Project') %>
<h3>Create your new Project!</h3>


<div class="row">
  <div class="col-md-8">
    <%= form_for(@project) do |f| %>
    	<%= render 'shared/error_messages', object: f.object %>
			<br>

      <%= f.text_field :name %>
			<%= f.label :name %>
			<br>

      <%= f.submit "New Project", class: "btn btn-success btn-sm" %>
    <% end %>
<p class="text-info">Project can be a family member(not registered in the system),an activity or even a small business
<strong>for whom you want to keep a separate accounting.</strong> </p>
  </div>
</div>

app/views/shared/_projects_info.html.erb
  <div class="span8">
    <% if @group.projects.any? %>
      <h4>Projects <span class="badge"><%= @group.projects.count %></span></h4>
      <ol class="projects">
        <%= render @projects %>
      </ol>
      
    <% end %>
  </div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="#">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="#">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user), current_user %>

  <h1 class="text-success"><%= current_user.name %></h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>

app/views/shared/_video_youtube.html.erb
			
			
<iframe width="560" height="315" src="//www.youtube.com/embed/p3vaG7R0wM4?rel=0" frameborder="0" allowfullscreen></iframe>