config/routes.rb
WealthOZ201::Application.routes.draw do

  resources :budgets

  resources :ledgers do
    collection do
      get :report_balance
      get :report_plm
      get :report_plwu
      get :report_kpi

    end
  end

  resources :cut_off_wealths

  resources :future_reports, only: [:index] do
    collection do
      get :future_balance
      get :actual_budget
    end
  end

  resources :transparents, only: []  do
  collection do
      get :report_balance
      get :report_plm
      get :report_plwu
      get :report_kpi
      get :report_story
    end
  end
  match '/transparent',   to: 'transparents#report',   via: 'get'

  match '/report',   to: 'ledgers#report',   via: 'get'
  match '/wealthoz',   to: 'ledgers#wealthoz',   via: 'get'
  match '/wealth_index',   to: 'ledgers#wealth_index',   via: 'get'
  resources :fxes
  resource :group do
    resources :group_users, controller: 'groups/group_users', only: [:index] do
      member do
        get :approved
      end
    end
  end

  resources :users do
    member do
      get :following, :followers
    end

  end
  resource :group_user

  resources :relationships, only: [:create, :destroy]

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :projects
  resources :accounts do
    collection do
      get :check
    end
  end

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/why',    to: 'static_pages#why',    via: 'get'
  match '/how',   to: 'static_pages#how',   via: 'get'
  match '/manage_groups',   to: 'static_pages#manage_groups',   via: 'get'

  match '/donate',   to: 'static_pages#donate',   via: 'get'

  match '/book',   to: 'static_pages#book',   via: 'get'
  match '/a2',   to: 'static_pages#a2',   via: 'get'
  match '/a3',   to: 'static_pages#a3',   via: 'get'

  match '/b1',   to: 'static_pages#b1',   via: 'get'
  match '/d1',   to: 'static_pages#d1',   via: 'get'
  match '/d2',   to: 'static_pages#d2',   via: 'get'

  match '/d4',   to: 'static_pages#d4',   via: 'get'

end

app/controllers/future_reports_controller.rb
class FutureReportsController < ApplicationController

  # def index
  #
  # end
  def future_balance
    @current_group = current_user.group
    authorize(@current_group, :view?)
    @fx = @current_group.fx.fx
    
    @accounts_bs = @current_group.accounts.where(fs_id: [1,2])

    if params[:end_date]
      ledgers = @current_group.ledgers.where('post_date < ?', Date.parse(params[:end_date]))
      budgets = @current_group.budgets.where('budget_date < ?', Date.parse(params[:end_date])).where('budget_date > ?', ledgers.last.post_date)
    else
      ledgers = @current_group.ledgers
      budgets = @current_group.budgets.where('budget_date > ?', ledgers.last.post_date)
    end

    ledgers_bs = ledgers.joins(:account).where('fs_id = 1 OR fs_id = 2')
    budgets_bs = budgets.joins(:account).where('fs_id = 1 OR fs_id = 2')

    @all_transactions = ledgers_bs + budgets_bs

    @all_transactions_hash_bs = @all_transactions.group_by(&:wunit).sort_by {|k,v| k}.reverse.map do |k, v|
      [k, v.group_by(&:account_id)]
    end

    chart_transactions =  Hash[@all_transactions_hash_bs]

    @account_hash_bs = @all_transactions.group_by(&:account_id)

    testo = Hash[@account_hash_bs.map {|k, v| [k, v.group_by(&:wunit)]}]

    @chart_future_balance = LazyHighCharts::HighChart.new('column') do |f|
      f.chart(:width => 800)
      @accounts_bs.each do |account|
          data = chart_transactions.keys.map  do |wunit|
          if testo[account.id] && testo[account.id][wunit]
            testo[account.id][wunit].inject(0) { |sum, obj| sum + obj.ammount }.to_i
          else
            0
          end

        end

        f.series(name: "#{account.name}",:data => data)
      end
       f.title({ :text=>"Future Balance by Wealth Units"})
       f.xAxis(:categories => chart_transactions.keys)
      #  f.yAxis(:title => {:text => "All amounts in " + @fx})
       f.options[:chart][:defaultSeriesType] = "column"
       f.legend(:align => 'right', :verticalAlign => 'top', :y => 75, :x => -50, :layout => 'vertical',)
       f.plot_options(:column=>{:stacking => 'bar'})
     end

  end
  alias_method  :index, :future_balance

  def actual_budget
    @current_group = current_user.group
    @fx = @current_group.fx.fx
    @accounts_pl = @current_group.accounts.where(fs_id: [3,4])

    if params[:start_date] && params[:end_date]
      # raise "#{Date.parse(params[:start_date]).beginning_of_day} | #{Date.parse(params[:end_date]).beginning_of_day}".inspect
      ledgers = @current_group.ledgers.where(post_date: Date.parse(params[:start_date]).beginning_of_day..Date.parse(params[:end_date]).end_of_day)
      budgets = @current_group.budgets.where(budget_date: Date.parse(params[:start_date]).beginning_of_day..Date.parse(params[:end_date]).end_of_day)
    else
      ledgers = @current_group.ledgers
      budgets = @current_group.budgets
    end

    @ledgers_pl = ledgers.joins(:account).where(accounts: { fs_id: [3,4] })
    @budgets_pl = budgets.joins(:account).where(accounts: { fs_id: [3,4] })

    @ledgers_hash_pl = @ledgers_pl.group_by(&:account_id)
    @budgets_hash_pl = @budgets_pl.group_by(&:account_id)

    @total = {}
    @accounts_pl.each do |account|
      actual = @ledgers_hash_pl[account.id].inject(0) { |sum, obj| sum + obj.ammount } if @ledgers_hash_pl[account.id]
      budget = @budgets_hash_pl[account.id].inject(0) { |sum, obj| sum + obj.ammount } if @budgets_hash_pl[account.id]
      @total[account.id] = actual.to_i - budget.to_i if budget || actual
    end

    account_chart = @accounts_pl.map(&:name)

    actual_chart, budget_chart = [], []
    @accounts_pl.each do |account|
      group = @ledgers_hash_pl.fetch(account.id, 0)
      if group.kind_of?(Array)
        actual_chart << group.inject(0) { |sum, obj| sum + obj.ammount }
      else
        actual_chart << group
      end
    end

    @accounts_pl.each do |account|
      group = @budgets_hash_pl.fetch(account.id, 0)
      if group.kind_of?(Array)
        budget_chart << group.inject(0) { |sum, obj| sum + obj.ammount }
      else
        budget_chart << group
      end
    end


    @chart_actual_budget = LazyHighCharts::HighChart.new('column') do |f|
       f.chart(:width => 800)
       f.series(:name=>'Actual',:data=> actual_chart.map(&:to_i))
       f.series(:name=>'Budget',:data=> budget_chart.map(&:to_i))
       f.title({ :text=>"Actual vs Budget (Income and Expenses)"})
       f.xAxis(:categories => account_chart)
      #  f.yAxis(:title => {:text => "All amounts in " + @fx})
       f.options[:chart][:defaultSeriesType] = "bar"
       f.legend(:align => 'right', :verticalAlign => 'top', :y => 75, :x => -50, :layout => 'vertical',)
       f.plot_options(:bar=>{:dataLabels => {:enabled => "true",:color=>"black",}})
     end



  end


end

app/views/future_reports/_actual_budget.html.haml
.pull-right
  = form_tag actual_budget_future_reports_path, remote: true, method: :get do
    = text_field_tag 'start_date',nil, class: 'form-control', placeholder: 'Start date', data: {behaviour: 'datepicker'}
    = text_field_tag 'end_date',nil, class: 'form-control', placeholder: 'End date', data: {behaviour: 'datepicker'}
    = submit_tag 'submit', class: 'btn btn-primary btn-sm'
%h3="Actual vs Budgeted from #{params[:start_date]} to #{params[:end_date]}"
%p="All amounts in "+@fx
%table{:class => "table table-striped table-hover ", :id => "act-bud"}
  %thead
    %tr{:class => "success"}
      %th Account
      %th Actual
      %th Budget
      %th Difference
  %tbody
    - @accounts_pl.each do |account|
      %tr{:class => ""}
        %td
          = account.name
        %td
          -if @ledgers_hash_pl[account.id]
            = @ledgers_hash_pl[account.id].inject(0) { |sum, obj| sum + obj.ammount }
        %td
          -if @budgets_hash_pl[account.id]
            = @budgets_hash_pl[account.id].inject(0) { |sum, obj| sum + obj.ammount }
        %td
          = @total[account.id]
    %tr{:class => "info"}
      %td
        %b Wealth for the period
      %td
        %b
          = number_with_precision( @ledgers_pl.map(&:ammount).inject(0, &:+),precision: 2, separator: '.', delimiter: ',')
      %td
        %b
          = number_with_precision( @budgets_pl.map(&:ammount).inject(0, &:+),precision: 2, separator: '.', delimiter: ',')
      %td
        %b= number_with_precision( @total.inject(0) {|sum, (k, v)| sum + v }, precision: 2, separator: '.', delimiter: ',')
= high_chart("my_id10", @chart_actual_budget)

app/views/future_reports/_future_balance.html.haml
%h3= "Future Balance Sheet as of #{params[:end_date]}"
%p="All amounts in "+@fx
.pull-right
  = form_tag future_balance_future_reports_path, remote: true, method: :get do
    = text_field_tag 'end_date', nil, class: 'form-control', placeholder: 'End date', data: { behaviour: 'datepicker' }
    = submit_tag 'submit', class: 'btn btn-primary btn-sm'

%table{:class => "table table-striped table-hover ", :id => "bs_future"}
  %thead
    %th{:class => "success"} Accounts\Wealth Units
    - @all_transactions_hash_bs.each do |wunit, ledegers|
      %td{:class => "success"}
        %strong= wunit
    %th{:class => "success"} Total
  %tbody
    - @accounts_bs.each do |account|
      %tr{:class => ""}
        %td{:class => ""}
          = account.name
        - @all_transactions_hash_bs.each do |k, v|
          %td{:class => ""}
            - if v[account.id]
              =number_with_precision( v[account.id].map(&:ammount).inject(0, &:+),precision: 2, separator: '.', delimiter: ',')
        %td{:class => ""}
          - if @account_hash_bs[account.id]
            =number_with_precision( @account_hash_bs[account.id].map(&:ammount).inject(0, &:+),precision: 2, separator: '.', delimiter: ',')
    %tr{:class => "info"}
      %td
        %strong Accumulated Wealth
      - @all_transactions_hash_bs.each do |k, v|
        %td
          %strong=number_with_precision( v.values.flatten.map(&:ammount).inject(0, &:+),precision: 2, separator: '.', delimiter: ',')
      %td
        %strong=number_with_precision( @account_hash_bs.values.flatten.map(&:ammount).inject(0, &:+),precision: 2, separator: '.', delimiter: ',')
= high_chart("my_id5", @chart_future_balance)

app/views/future_reports/actual_budget.js.erb
$('#actual_budget').html("<%=j render('future_reports/actual_budget') %>")
$('#end_date, #start_date').datepicker({
  weekStart: 1,
  autoclose: true,
  format:'yyyy-mm-dd' ,
  todayHighlight: true
})

app/views/future_reports/future_balance.js.erb
$('#future_balance').html("<%= j render('future_reports/future_balance') %>")
$('#end_date').datepicker({
                      weekStart: 1,
                      autoclose: true,
                      format:'yyyy-mm-dd' ,
                      todayHighlight: true
                    });

app/views/future_reports/index.html.haml
%section
  %ul.nav.nav-tabs{style: "margin-bottom: 15px"}
    %li
      %h5
        = current_user.group.name
    %li.active
      = link_to 'Future Balance', future_balance_future_reports_path, remote: true, data: { target: '#future_balance', toggle: 'tab'}
    %li
      = link_to 'Actual vs Budget', actual_budget_future_reports_path, remote: true, data: { target: '#actual_budget', toggle: 'tab'}
    -# %li
    -#   = link_to 'P&L Wealth Unit', report_plwu_ledgers_path, remote: true, data: { target: '#plwu', toggle: 'tab'}
    -# %li
    -#   = link_to "KPI's", report_kpi_ledgers_path, remote: true, data: { target: '#kpi', toggle: 'tab'}

#myTabContent.tab-content
  #future_balance.tab-pane.fade.active.in
    = render 'future_reports/future_balance'
  #actual_budget.tab-pane.fade
  -# #plwu.tab-pane.fade
  -# #kpi.tab-pane.fade