config/routes.rb
WealthOZ201::Application.routes.draw do

  resources :budgets

  resources :ledgers do
    collection do
      get :report_balance
      get :report_plm
      get :report_plwu
      get :report_kpi

    end
  end

  resources :cut_off_wealths

  resources :future_reports, only: [:index] do
    collection do
      get :future_balance
      get :actual_budget
    end
  end

  resources :transparents, only: []  do
  collection do
      get :report_balance
      get :report_plm
      get :report_plwu
      get :report_kpi
      get :report_story
    end
  end
  match '/transparent',   to: 'transparents#report',   via: 'get'

  match '/report',   to: 'ledgers#report',   via: 'get'
  match '/wealthoz',   to: 'ledgers#wealthoz',   via: 'get'
  match '/wealth_index',   to: 'ledgers#wealth_index',   via: 'get'
  resources :fxes
  resource :group do
    resources :group_users, controller: 'groups/group_users', only: [:index] do
      member do
        get :approved
      end
    end
  end

  resources :users do
    member do
      get :following, :followers
    end

  end
  resource :group_user

  resources :relationships, only: [:create, :destroy]

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :projects
  resources :accounts do
    collection do
      get :check
    end
  end

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/why',    to: 'static_pages#why',    via: 'get'
  match '/how',   to: 'static_pages#how',   via: 'get'
  match '/manage_groups',   to: 'static_pages#manage_groups',   via: 'get'

  match '/donate',   to: 'static_pages#donate',   via: 'get'

  match '/book',   to: 'static_pages#book',   via: 'get'
  match '/a2',   to: 'static_pages#a2',   via: 'get'
  match '/a3',   to: 'static_pages#a3',   via: 'get'

  match '/b1',   to: 'static_pages#b1',   via: 'get'
  match '/d1',   to: 'static_pages#d1',   via: 'get'
  match '/d2',   to: 'static_pages#d2',   via: 'get'

  match '/d4',   to: 'static_pages#d4',   via: 'get'

end

app/models/ledger.rb
class Ledger < ActiveRecord::Base
  belongs_to :account
  belongs_to :group
  default_scope -> { order('created_at DESC') }
  
  validates :group_id, :wunit, :ammount,:post_date, presence: true

end

app/controllers/ledgers_controller.rb
class LedgersController < ApplicationController
  before_action :set_ledger, only: [:show, :edit, :update, :destroy]
  before_action :set_data, only: [:report, :report_balance, :report_plm, :report_plwu, :report_kpi]

  def index
    current_group = current_user.group
    authorize(current_group)

    #All Group transaction
    @ledgers = current_group.ledgers
  end

  def show
    @ledger = Ledger.find(params[:id])
  end

  def new
   current_group = current_user.group
   authorize(current_group)

    @accounts = current_group.accounts.group_by(&:fs).map do |k,v|
      [k.report_class, v.map {|el|  [el.name, el.id] }]
    end

   @wunit = {
              Projects: current_group.projects.pluck(:name),
              People: current_group.users.pluck(:name)
            }
   @ledger = Ledger.new


  end

  # GET /ledgers/1/edit
  def edit
    current_group = current_user.group
    @accounts = current_group.accounts
    @users =  current_group.users
    @projects = current_group.projects

    @wunits = @users + @projects

  end


  def create
    current_group = current_user.group

    current_group.ledgers.create(ledger_params[:ledgers])

    respond_to do |format|
      # if @ledger.save
        format.html { redirect_to :back, notice: 'A New Transaction was successfully created.' }
        format.json { render action: 'index', status: :created, location: @ledger }
        format.js
      # else
      #   format.html { render action: 'new' }
      #   format.json { render json: @ledger.errors, status: :unprocessable_entity }
      # end
    end
  end

  def update
    respond_to do |format|
      if @ledger.update(single_ledger_params)
        format.html { redirect_to ledgers_url , notice: 'Transaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'index' }
        format.json { render json: @ledger.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @ledger.destroy
    respond_to do |format|
      format.html { redirect_to ledgers_url }
      format.json { head :no_content }
    end
  end


  def report_balance
  #  #Balance Sheet accounts
    authorize(@current_group, :view?)

    @accounts_bs = @current_group.accounts.where(fs_id: [1,2,5])
    @accounts_bs_a = @current_group.accounts.where(fs_id: 1)
    @accounts_bs_d = @current_group.accounts.where(fs_id: 2)
  #
    if params[:end_date]
      @ledgers = @current_group.ledgers.where('post_date <= ?', Date.parse(params[:end_date]))
    else
      @ledgers = @current_group.ledgers
    end
  #
    # @ledgers_bs = @ledgers.joins(:account).where(fs_id: [1,2,5])
    @ledgers_bs = @ledgers.joins(:account).where('fs_id = 1 OR fs_id = 2 OR fs_id = 5')
  #

    @ledgers_hash_bs = @ledgers_bs.group_by(&:wunit).sort_by {|k,v| k}.reverse.map do |k, v|
      [k, v.group_by(&:account_id)]
    end
  #
    @account_hash_bs = @ledgers_bs.group_by(&:account_id)
  #
  #
  #   #Draw Assets by WU
    @ledgers_bs_a = @ledgers.joins(:account).where('fs_id = 1')
    ledger_hash_a_summed = Hash[@ledgers_bs_a.group_by(&:wunit).map {|k, v| [k, v.reduce(0) {|sum, ledger| sum + ledger.ammount }]}]

  #
  #   #Draw Debt by WU !!! Problem if Wealth Unit has Debt but no Assets it wont appear on the graph
    @ledgers_bs_d = @ledgers.joins(:account).where('fs_id = 2')
    ledger_hash_d_summed = Hash[@ledgers_bs_d.group_by(&:wunit).map {|k, v| [k, v.reduce(0) {|sum, ledger| sum + ledger.ammount }]}]

    wunits = @current_group.users.pluck(:name) + @current_group.projects.pluck(:name)
    graph_assets =   wunits.map {|el| ledger_hash_a_summed.fetch(el, 0)}.as_json.map { |i| i.to_i }
    graph_debt =   wunits.map {|el| ledger_hash_d_summed.fetch(el, 0)}.as_json.map { |i| i.to_i }

    @chart_bs = LazyHighCharts::HighChart.new('column') do |f|
      f.chart(:width => 900 )
      f.series(:name=>'Assets',:data=> graph_assets )
      f.series(:name=>'Debt',:data=> graph_debt )
      f.title({ :text=>"Balance Sheet by Wealth Units " })
      f.xAxis(:categories => wunits )
      f.yAxis(:title => {:text => "All amounts in " + @fx})
      f.options[:chart][:defaultSeriesType] = "bar"
      f.legend(:align => 'right', :verticalAlign => 'top', :y => 75, :x => -50, :layout => 'vertical',)
      f.plot_options(:bar=>{:stacking=>"normal",:dataLabels => {:enabled => "true",:color=>"grey"}})

    end
  end

  def report_plm
    if params[:date]
      @ledgers = @current_group.ledgers.where('extract(year  from post_date) = ?', params[:date][:year])
      # .where('post_date <= ?', Date.parse(params[:date][:year]))
    else
      @ledgers = @current_group.ledgers
    end


    @accounts_pl = @current_group.accounts.where('fs_id = 3 OR fs_id = 4')
    @ledgers_pl = @ledgers.joins(:account).where('fs_id = 3 OR fs_id = 4')
    @ledgers_hash_pl_m = @ledgers_pl.group_by{ |m| m.post_date.beginning_of_month}.sort_by {|k,v| k}.map do |k, v|
      [k, v.group_by(&:account_id)]
    end
    @account_hash_pl = @ledgers_pl.group_by(&:account_id)


    #chart
    #Draw Expenses by M
    @ledgers_expenses = @ledgers.joins(:account).where('fs_id = 4')
    @hash_expenses_m = @ledgers_expenses.group_by{ |item| item.post_date.beginning_of_month }
    # ledger_hash_a_summed = Hash[@ledgers_bs_a.group_by(&:wunit).map {|k, v| [k, v.reduce(0) {|sum, ledger| sum + ledger.ammount }]}]

    ledger_hash_expenses_summed = {}
    @ledgers_expenses.each do |item|
      key = item.post_date.beginning_of_month.month
      ledger_hash_expenses_summed[key] = 0 unless ledger_hash_expenses_summed[key]
      ledger_hash_expenses_summed[key] += item[:ammount]
    end

    #Draw Income by M
    @ledgers_income = @ledgers.joins(:account).where('fs_id = 3')
    @hash_income_m = @ledgers_income.group_by{ |item| item.post_date.beginning_of_month }
    ledger_hash_income_summed = {}
    @ledgers_income.each do |item|
      key = item.post_date.beginning_of_month.month
      ledger_hash_income_summed[key] = 0 unless ledger_hash_income_summed[key]
      ledger_hash_income_summed[key] += item[:ammount]
    end

    months = (1..12).to_a
    graph_income = months.map {|el| ledger_hash_income_summed.fetch(el, 0)}.as_json.map { |i| i.to_i }
    graph_expense = months.map {|el| ledger_hash_expenses_summed.fetch(el, 0)}.as_json.map { |i| i.to_i }
    graph_invest = graph_income.zip(graph_expense).map { |x, y| y + x }

    @chart_pl_m = LazyHighCharts::HighChart.new('column') do |f|
      f.chart(:width => 900)
      f.series(:type=> 'column',:name=>'Income',:data=> graph_income )
      f.series(:type=> 'column',:name=>'Expenses',:data=> graph_expense )
      f.series(:type=> 'spline',:name=> 'Investments(Borrowings)', :data=> graph_invest)
      f.title({ :text=>"Profit and Loss by Months"})
      f.xAxis(:categories => months, :title => {:text => "All amounts in " + @fx})
      f.options[:chart][:defaultSeriesType] = "column"
      f.legend(:align => 'top', :verticalAlign => 'left',:y=>20, :layout => 'horizontal',)
      f.plot_options(:column=>{:stacking=>"normal",})
    end

  end

  def report_plwu
    @accounts_pl = @current_group.accounts.where('fs_id = 3 OR fs_id = 4')
    if params[:start_date] && params[:end_date]
      @ledgers = @current_group.ledgers.where(post_date: Date.parse(params[:start_date]).beginning_of_day..Date.parse(params[:end_date]).end_of_day)
    else
      @ledgers = @current_group.ledgers
    end

    #Profit&Loss Transactions
    @ledgers_pl = @ledgers.joins(:account).where('fs_id = 3 OR fs_id = 4')

    #HAshes

    @ledgers_hash_pl = @ledgers_pl.group_by(&:wunit).sort_by {|k,v| k}.reverse.map do |k, v|
      [k, v.group_by(&:account_id)]
    end
   #Accounts
    @account_hash_pl = @ledgers_pl.group_by(&:account_id)


   #Charts
    #Draw Expenses by WU
    @ledgers_expenses = @ledgers.joins(:account).where('fs_id = 4')
    @hash_expenses_w = @ledgers_expenses.group_by{ |item| item[:wunit] }
    ledger_hash_expensesw_summed = {}
    @ledgers_expenses.each do |item|
    key = item[:wunit]
    ledger_hash_expensesw_summed[key] = 0 unless ledger_hash_expensesw_summed[key]
    ledger_hash_expensesw_summed[key] += item[:ammount]
    end

    #Draw Income by WU
    @ledgers_income = @ledgers.joins(:account).where('fs_id = 3')

    @hash_income_w = @ledgers_income.group_by{ |item| item[:wunit] }
    ledger_hash_incomew_summed = {}
    @ledgers_income.each do |item|
    key = item[:wunit]
    ledger_hash_incomew_summed[key] = 0 unless ledger_hash_incomew_summed[key]
    ledger_hash_incomew_summed[key] += item[:ammount]
    end

    wunits = @current_group.users.pluck(:name) + @current_group.projects.pluck(:name)
    graph_expensew = wunits.map {|el| ledger_hash_expensesw_summed.fetch(el, 0)}.as_json.map { |i| i.to_i }
    graph_incomew = wunits.map {|el| ledger_hash_incomew_summed.fetch(el, 0)}.as_json.map { |i| i.to_i }


   @chart_pl_w = LazyHighCharts::HighChart.new('column') do |f|
      f.chart(:width => 900)
      f.series(:name=>'Income',:data=> graph_incomew)
      f.series(:name=>'Expenses',:data=> graph_expensew  )
      f.title({ :text=>"Profit and Loss by Wealth Units"})
      f.xAxis(:categories => wunits)
      f.yAxis(:title => {:text => "All amounts in " + @fx})
      f.options[:chart][:defaultSeriesType] = "bar"
      f.legend(:align => 'right', :verticalAlign => 'top', :y => 75, :x => -50, :layout => 'vertical',)
      f.plot_options(:bar=>{:stacking=>"normal",:dataLabels => {:enabled => "true",:color=>"black",}})
    end
  end

  def report_kpi
    @ledgers = @current_group.ledgers

    @accounts_bs = @current_group.accounts.where('fs_id = 1 OR fs_id = 2 OR fs_id = 5')
    @accounts_bs_a = @current_group.accounts.where('fs_id = 1')
    @accounts_bs_d = @current_group.accounts.where('fs_id = 2')


    @ledgers_pl = @ledgers.joins(:account).where('fs_id = 3 OR fs_id = 4')

   #Profit and loss accounts
    @accounts_pl = @current_group.accounts.where('fs_id = 3 OR fs_id = 4')

app/helpers/ledgers_helper.rb
module LedgersHelper
  def default_or_select_year
    if params[:date] && params[:date][:year]
      params[:date][:year].to_i
    else
      Date.today
    end
  end

end

app/views/ledgers/reports/_report_balance.html.haml
-if params[:end_date]
  %h3
    = "Balance Sheet by Wealth Units as of #{params[:end_date]}"
-else
  %h3 Balance Sheet by Wealth Units
%div.row
  %div.col-md-6
    %p="All amounts in "+ @fx
  %div.col-md-6
    %div.pull-right
      = form_tag report_balance_ledgers_path, remote: true, method: :get do
        = text_field_tag 'end_date',nil, class: 'form-control', placeholder: 'End date'
        = submit_tag 'submit', class: 'btn btn-primary btn-sm'


%table{:class => "table table-striped table-hover ", :id => "bs_table"}
  %thead
    %th{:class => "success"} Accounts\Wealth Units
    - @ledgers_hash_bs.each do |wunit, ledegers|
      %td{:class => "success"}
        %strong= wunit
    %th{:class => "success"} Total
  %tbody
    - @accounts_bs.each do |account|
      %tr{:class => ""}
        %td
          = account.name
        - @ledgers_hash_bs.each do |k, v|
          %td
            - if v[account.id]
              =number_with_precision( v[account.id].map(&:ammount).inject(0, &:+),precision: 2, separator: '.', delimiter: ',')
        %td
          - if @account_hash_bs[account.id]
            =number_with_precision( @account_hash_bs[account.id].map(&:ammount).inject(0, &:+),precision: 2, separator: '.', delimiter: ',')

    %tr{:class => "info"}
      %td
        %strong Accumulated Wealth
      - @ledgers_hash_bs.each do |k, v|
        %td
          %strong=number_with_precision( v.values.flatten.map(&:ammount).inject(0, &:+),precision: 2, separator: '.', delimiter: ',')
      %td
        %strong=number_with_precision( @account_hash_bs.values.flatten.map(&:ammount).inject(0, &:+),precision: 2, separator: '.', delimiter: ',')
= render 'ledgers/chart_bs'

app/views/ledgers/reports/_report_kpi.html.haml
=render 'chart_index'
<div class="col-md-10" id='chart'>
</div>
= render_chart @chart_ratio, "chart"
<div class="col-md-10">

.row
  .col-md-6
    = wealth_assets_text(@wealth_assets)
  .col-md-6
    = margin_text(@margin)

=@graph_index1

app/views/ledgers/reports/_report_plm.html.haml
-if params[:date]
  %h3
    = " Profit & Loss Monthly for #{params[:date].values.map(&:to_i)}"
-else
  %h3  Profit & Loss Monthly

%div.row
  %div.col-md-6
    %p="All amounts in "+ @fx
  %div.col-md-6
    %div.pull-right
      = form_tag report_plm_ledgers_path, remote: true, method: :get do
        = select_year(default_or_select_year, start_year: (Time.now - 8.year).year, end_year: (Time.now + 1.year).year)
        = submit_tag 'submit', class: 'btn btn-primary btn-sm'
%table{:class => "table table-striped table-hover ", :id => "pl_m_table" }
  %thead
    %th{:class => "success"} Accounts\Months
    - @ledgers_hash_pl_m.each do |m, ledegers|
      %td{:class => "success"}
        %strong= m.month
    %th{:class => "success"} Total
  %tbody
    - @accounts_pl.each do |account|
      %tr{:class => ""}
        %td
          = account.name
        - @ledgers_hash_pl_m.each do |k, v|
          %td
            - if v[account.id]
              =number_with_precision(  v[account.id].map(&:ammount).inject(0, &:+),precision: 2, separator: '.', delimiter: ',')
        %td
          - if @account_hash_pl[account.id]
            =number_with_precision( @account_hash_pl[account.id].map(&:ammount).inject(0, &:+),precision: 2, separator: '.', delimiter: ',')
    %tr{:class => "info"}
      %td
        %strong Wealth for the period
      - @ledgers_hash_pl_m.each do |k, v|
        %td
          %strong=number_with_precision(v.values.flatten.map(&:ammount).inject(0, &:+),precision: 2, separator: '.', delimiter: ',')
      %td
        %strong=number_with_precision(@account_hash_pl.values.flatten.map(&:ammount).inject(0, &:+),precision: 2, separator: '.', delimiter: ',')
=render 'chart_pl_m'

app/views/ledgers/reports/_report_plwu.html.haml
-if params[:end_date]
  %h3
    = "Profit & Loss by Wealth Units for the period #{params[:start_date]} to #{params[:end_date]}"
-else
  %h3 Profit & Loss by Wealth Units

%div.row
  %div.col-md-6
    %p="All amounts in "+ @fx
  %div.col-md-6
    %div.pull-right
      = form_tag report_plwu_ledgers_path, remote: true, method: :get do
        = text_field_tag 'start_date',nil, class: 'form-control', placeholder: 'Start date', data: {behaviour: 'datepicker'}
        = text_field_tag 'end_date',nil, class: 'form-control', placeholder: 'End date', data: {behaviour: 'datepicker'}
        = submit_tag 'submit', class: 'btn btn-primary btn-sm'

<script type="text/javascript">
$('[data-behaviour~=datepicker]').datepicker({
weekStart: 1,
autoclose: true,
format:'yyyy-mm-dd' ,
todayHighlight: true
});
</script>

%table{:class => "table table-striped table-hover ", :id => "pl_w_table"  }
  %thead
    %th{:class => "success"}  Accounts\Wealth Units
    - @ledgers_hash_pl.each do |wunit, ledegers|
      %td{:class => "success"}
        %strong= wunit
    %th{:class => "success"} Total
  %tbody
    - @accounts_pl.each do |account|
      %tr{:class => ""}
        %td
          = account.name
        - @ledgers_hash_pl.each do |k, v|
          %td
            - if v[account.id]
              =number_with_precision(  v[account.id].map(&:ammount).inject(0, &:+),precision: 2, separator: '.', delimiter: ',')
        %td
          - if @account_hash_pl[account.id]
            =number_with_precision( @account_hash_pl[account.id].map(&:ammount).inject(0, &:+),precision: 2, separator: '.', delimiter: ',')
    %tr{:class => "info"}
      %td
        %strong Wealth for the period
      - @ledgers_hash_pl.each do |k, v|
        %td
          %strong=number_with_precision(v.values.flatten.map(&:ammount).inject(0, &:+),precision: 2, separator: '.', delimiter: ',')
      %td
        %strong=number_with_precision(@account_hash_pl.values.flatten.map(&:ammount).inject(0, &:+),precision: 2, separator: '.', delimiter: ',')
=render 'chart_pl_w'